### ISSUE TITLE
New Issue on start.sh due to last changes

### ISSUE THREAD

**Issue by CTOArtUp** [affidaty-blockchain/trinci-node#1]
I have error messages after the node startup.
![Schermata da 2022-02-23 20-44-54](https://user-images.githubusercontent.com/95364279/155396143-697130a7-3660-4235-9f94-2f46f1db3ee2.png)

**Comment by trinci-blockchain** [comment]
Hi, I saw the closure of the issue, I confirm that the report does not identify a problem, but rather a required functionality, that is, if a node, with an old or incompatible core, tries to send an invalid block, not authorized or with a structure incompatible, the single node discards it and in the log you see exactly that error, which however should not be interpreted as a core error, but as a warning.
We still collect the issue to change from error to warning because it could be misleading.
